---
- name: "SSH | Check weak Diffie-Hellman moduli existance"  # noqa no-changed-when
  ansible.builtin.shell:
    cmd: grep "2 6 100 2047" /etc/ssh/moduli | head -1
  args:
    executable: /bin/bash
  register: result
  ignore_errors: true

- name: "SSH | Remove Diffie-Hellman moduli smaller than 3071"
  ansible.builtin.shell:
    cmd: "awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.safe && mv /etc/ssh/moduli.safe /etc/ssh/moduli"
  args:
    executable: /bin/bash
  when: result.rc == 0
  notify: "Restart ssh"

- name: "SSH | Copy sshd_config template"
  ansible.builtin.template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    mode: "0644"
    owner: root
    group: root
    backup: true
    validate: /usr/sbin/sshd -t -f %s
  notify: "Restart ssh"
