---
- name: "Restart ssh"
  ansible.builtin.systemd:
    name: ssh
    state: restarted
    enabled: true
    daemon_reload: true
  when: ansible_os_family == 'Debian'

- name: "Restart ssh"
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    enabled: true
    daemon_reload: true
  when: ansible_os_family == 'RedHat'
